---
title: "Simulation2"
author: "Leona"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set-up
```{r}
# load libraries 
library(tidyverse)
library(MASS)
library(dplyr)

# set seed 
set.seed(294)

# set number of data points
n <- 1000
```

# generate protected attributes
```{r}
# gender
gender <- as.factor(sample(c("Female", "Male"), n, replace = TRUE))

# ethnicity
#ethnicity <- sample(c("Minority", "Majority"), n, replace = TRUE, prob = c(0.35, 0.65)

# disability
#disability <- sample(c("Yes", "No"), n, replace = TRUE), prob = c(0.05, 0.95)
```

# generate base variable (education)
```{r}
education <- sample(1:3, n, replace = T, prob = c(0.2, 0.5, 0.3))

data <- as.data.frame(gender)
data$education <- as.factor(education)
```

# generate income variable
```{r}
# generate income variable
m_income <- c("1" = 30000, "2" = 50000, "3" = 70000)

generate_income <- function(education_level, gender){
  mean_income <- m_income[as.character(education_level)]
  sd_income <- 10000 # SD for noise
  
  # generate normally distributed incomes
  incomes <- abs(rnorm(1000, mean = mean_income, sd = sd_income))
  
  # calculate the mean of the incomes
  mean_income_all <- mean(incomes)
  
  # split incomes based on mean
  below_mean <- incomes[incomes < mean_income_all]
  above_mean <- incomes[incomes >= mean_income_all]
  
  # two candidate incomes
  low_income <- sample(below_mean, 1)
  high_income <- sample(above_mean, 1)
  
  # sample differently for males and females, with females more likely to have lower income
  if(gender == "Female"){
    sample(c(low_income, high_income), 1, prob = c(0.7, 0.3))
  } else {
    sample(c(low_income, high_income), 1, prob = c(0.3, 0.7))
  }
}

data$income <- mapply(generate_income, data$education, data$gender)

# add noise to incomes
noise <- rnorm(n, mean = 0, sd = 4000)
data$income <- abs(data$income + noise)

# check income variable
summary(data$income)
summary(data[gender == "Female",]$income)
summary(data[gender == "Male",]$income)
```

# generate house ownership variable
```{r}
generate_house_ownership <- function(education_level, income){
  # base probabilities depending on education level
  base_prob <- c("1" = 0.15, "2" = 0.3, "3" = 0.45)
  prob <- base_prob[as.character((education_level))]
  
  # adjust probability based on income
  prob <- prob + (income - mean(data$income)) / (3 * sd(data$income))
  
  # add noise
  prob <- prob + rnorm(1, mean = 0, sd = 0.05)
  
  # ensure probability is between boundaries
  prob = min(max(prob, 0), 1)
  
  # sample house ownership
  sample(c(0,1), 1, prob = c(1- prob, prob))
}

# generate variable
data$house_ownership <- mapply(generate_house_ownership, data$education, data$income)

# inspect variable
table(data$gender, data$house_ownership)
table(data$education, data$house_ownership)

mean(data[data$house_ownership == 1,]$income)
mean(data[data$house_ownership == 0,]$income)
```

# generate outcome (committing crime)
```{r}
# Sigmoid function
sigmoid <- function(x){
  1 / (1 + exp(-x))
}

# weights for the variable
weights <- list(education = -0.2, income = -0.00003, house_ownership = -1.7)

# generate crime variable
generate_crime <- function(education, income, house_ownership) {
  # convert education to numeric
  education_numeric <- as.numeric((as.character(education)))
  
  # calculate linear combination
  linear_combination <- 2.5 + weights$education * education_numeric +
    weights$income * income +
    weights$house_ownership * house_ownership

  # apply Sigmoid function
  crime_prob <- sigmoid(linear_combination)

  # add noise
  crime_prob <- min(max(crime_prob + rnorm(1, mean = 0, sd = 0.05), 0), 1)

  # sample outcome on crime variable
  sample(c(0,1), 1, prob = c(1 - crime_prob, crime_prob))
}

data$crime <- mapply(generate_crime, data$education, data$income, data$house_ownership)

table(data$crime)
```

# Try model
```{r}
train <- sample(1:n, 0.8 * n)
data_train <- data[train,]
data_test <- data[-train,]

# Fit logistic regression model without sensitive attributes
model <- glm(crime ~ ., data = data_train, family = binomial)
predicted_outcome <- predict(model, data_test, type = "response")
test_outcome <- ifelse(predicted_outcome > 0.5, 1, 0)
summary(model)

# Model performance
confusion_matrix_g <- table(data_test$crime, test_outcome)
(confusion_matrix_g[1,1] + confusion_matrix_g[2,2]) / nrow(data_test) # accuracy
confusion_matrix_g[2,1] / nrow(data_test) # p false negative
confusion_matrix_g[1,2] / nrow(data_test) # p false positive

# Accuracy for subgroups
indices <- which(data_test$gender == "Female")
confusion_matrix_female <- table(data_test$crime[indices], test_outcome[indices])
(confusion_matrix_female[1,1] + confusion_matrix_female[2,2]) / length(indices) # accuracy
confusion_matrix_female[2,1] / length(indices) # p false negative
confusion_matrix_female[1,2] / length(indices) # p false positive
```

